# Generated by Django 3.2.5 on 2022-09-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eviction_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionRecord',
            fields=[
                ('case_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('court', models.CharField(blank=True, max_length=30, null=True)),
                ('case_caption', models.CharField(blank=True, max_length=120, null=True)),
                ('judge', models.CharField(blank=True, max_length=30, null=True)),
                ('filed_date', models.DateField()),
                ('case_type', models.CharField(blank=True, max_length=16, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=30, null=True)),
                ('disposition_date', models.DateField(blank=True, null=True)),
                ('plaintiff_name', models.CharField(blank=True, max_length=60, null=True)),
                ('plaintiff_address', models.TextField(blank=True, null=True)),
                ('plaintiff_attorney', models.CharField(blank=True, max_length=60, null=True)),
                ('defendant_name', models.CharField(blank=True, max_length=60, null=True)),
                ('defendant_address', models.TextField(blank=True, null=True)),
                ('defendant_attorney', models.CharField(blank=True, max_length=60, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eviction_records',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EvictionRecords',
        ),
    ]
