# Generated by Django 3.2.5 on 2022-09-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eviction_scraper', '0002_auto_20220920_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evictionrecord',
            options={'managed': True},
        ),
    ]
