# Generated by Django 3.2.5 on 2022-09-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eviction_scraper', '0003_alter_evictionrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionrecord',
            name='case_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evictionrecord',
            name='case_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
