# Generated by Django 3.2.5 on 2022-09-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eviction_scraper', '0004_auto_20220927_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionrecord',
            name='case_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
