# Generated by Django 3.2.5 on 2022-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eviction_scraper', '0005_alter_evictionrecord_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionrecord',
            name='case_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
